### ISSUE TITLE
CI: add basic CI

### ISSUE THREAD

**Issue by tylerjereddy** [tylerjereddy/rusty_hausdorff#2]
* I've not set up CI for a Rust project before, so probably a useful exercise anyway

- [x] `cargo check` -- added in #6
- [x] `cargo clippy` -- added in #9
- [x] `cargo fmt` -- added in #8
- [x] `cargo test` -- added in #7

**Comment by tylerjereddy** [comment]
Basic CI is now in place via MRs in checklist above, so closing.
